name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release-mode: [debug, fast, safe, small]
        include:
          - release-mode: debug
            test-opt: Debug
            build-args: ""
          - release-mode: fast
            test-opt: ReleaseFast
            build-args: "--release=fast"
          - release-mode: safe
            test-opt: ReleaseSafe
            build-args: "--release=safe"
          - release-mode: small
            test-opt: ReleaseSmall
            build-args: "--release=small"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Zig
        run: |
          wget -q https://ziglang.org/download/0.15.1/zig-linux-x86_64-0.15.1.tar.xz
          tar -xf zig-linux-x86_64-0.15.1.tar.xz
          sudo mv zig-linux-x86_64-0.15.1 /opt/zig
          sudo ln -s /opt/zig/zig /usr/local/bin/zig

      - name: Verify Zig installation
        run: zig version

      - name: Check formatting
        run: |
          zig fmt --check lib/src/
          zig fmt --check cli/src/
          zig fmt --check build.zig
          zig fmt --check lib/build.zig
          zig fmt --check cli/build.zig

      - name: Test with ${{ matrix.test-opt }} optimization
        run: zig test lib/src/main.zig -O${{ matrix.test-opt }}

      - name: Build with ${{ matrix.release-mode }} optimization
        run: zig build ${{ matrix.build-args }}
